// <auto-generated />
using System;
using FinanzasPersonales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanzasPersonales.Migrations
{
    [DbContext(typeof(FinanzasContext))]
    partial class FinanzasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanzasPersonales.Models.Corte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<decimal>("BalanceAlCorte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEgresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIngresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Anio", "Mes")
                        .IsUnique();

                    b.ToTable("Cortes");
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Egreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("RenglonEgresoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEgresoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPagoDefectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RenglonEgresoId");

                    b.HasIndex("TipoEgresoId");

                    b.HasIndex("TipoPagoDefectoId");

                    b.ToTable("Egresos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Compra Supermercado",
                            Estado = true,
                            RenglonEgresoId = 1,
                            TipoEgresoId = 1,
                            TipoPagoDefectoId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Compra colmado",
                            Estado = true,
                            RenglonEgresoId = 1,
                            TipoEgresoId = 1,
                            TipoPagoDefectoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Recarga combustible",
                            Estado = true,
                            RenglonEgresoId = 2,
                            TipoEgresoId = 1,
                            TipoPagoDefectoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Salida al cine",
                            Estado = true,
                            RenglonEgresoId = 3,
                            TipoEgresoId = 1,
                            TipoPagoDefectoId = 2
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Ingreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoIngresoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoIngresoId");

                    b.ToTable("Ingresos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Salario Base Unapec",
                            Estado = true,
                            Institucion = "Universidad APEC",
                            TipoIngresoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Salario Base Consultora AXP",
                            Estado = true,
                            Institucion = "Consultora AXP",
                            TipoIngresoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Bonificación Consultora",
                            Estado = true,
                            Institucion = "Consultora AXP",
                            TipoIngresoId = 4
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.RenglonEgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("RenglonesEgreso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Comida",
                            Estado = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Combustible",
                            Estado = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Recreación",
                            Estado = true
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Servicios",
                            Estado = true
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.TipoEgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposEgreso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Gasto",
                            Estado = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Inversión",
                            Estado = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Costo",
                            Estado = true
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.TipoIngreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposIngreso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Salario Base",
                            Estado = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Horas Extras",
                            Estado = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Comisiones",
                            Estado = true
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Bonificación",
                            Estado = true
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.TipoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TiposPago");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Efectivo",
                            Estado = true
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Tarjeta de Crédito",
                            Estado = true
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tarjeta de Débito",
                            Estado = true
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Cheque",
                            Estado = true
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Transferencia",
                            Estado = true
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("EgresoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IngresoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoTarjeta")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("TipoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EgresoId");

                    b.HasIndex("IngresoId");

                    b.HasIndex("TipoPagoId");

                    b.HasIndex("UsuarioId", "FechaTransaccion");

                    b.ToTable("Transacciones", t =>
                        {
                            t.HasCheckConstraint("CK_Transaccion_Concepto", "([TipoTransaccion] = 2 AND [EgresoId] IS NOT NULL AND [IngresoId] IS NULL) OR ([TipoTransaccion] = 1 AND [IngresoId] IS NOT NULL AND [EgresoId] IS NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaTransaccion = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IngresoId = 1,
                            Monto = 45000m,
                            TipoPagoId = 5,
                            TipoTransaccion = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaTransaccion = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IngresoId = 2,
                            Monto = 30000m,
                            TipoPagoId = 5,
                            TipoTransaccion = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 3,
                            EgresoId = 1,
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaTransaccion = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 8500m,
                            NoTarjeta = "4321",
                            TipoPagoId = 2,
                            TipoTransaccion = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 4,
                            EgresoId = 3,
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaTransaccion = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 3200m,
                            NoTarjeta = "8765",
                            TipoPagoId = 3,
                            TipoTransaccion = 2,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comentario = "Compra semanal",
                            EgresoId = 2,
                            Estado = true,
                            FechaRegistro = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaTransaccion = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 1250m,
                            TipoPagoId = 1,
                            TipoTransaccion = 2,
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("DiaCorte")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("LimiteEgresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("TipoPersona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "00100000009",
                            DiaCorte = 28,
                            Email = "demo@finanzas.com",
                            Estado = true,
                            LimiteEgresos = 25000m,
                            Nombre = "Usuario Demo",
                            Rol = 1,
                            TipoPersona = 1
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "00100000017",
                            DiaCorte = 28,
                            Email = "admin@finanzas.com",
                            Estado = true,
                            LimiteEgresos = 0m,
                            Nombre = "Administrador",
                            Rol = 2,
                            TipoPersona = 1
                        });
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Corte", b =>
                {
                    b.HasOne("FinanzasPersonales.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Egreso", b =>
                {
                    b.HasOne("FinanzasPersonales.Models.RenglonEgreso", "RenglonEgreso")
                        .WithMany()
                        .HasForeignKey("RenglonEgresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasPersonales.Models.TipoEgreso", "TipoEgreso")
                        .WithMany()
                        .HasForeignKey("TipoEgresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasPersonales.Models.TipoPago", "TipoPagoDefecto")
                        .WithMany()
                        .HasForeignKey("TipoPagoDefectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RenglonEgreso");

                    b.Navigation("TipoEgreso");

                    b.Navigation("TipoPagoDefecto");
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Ingreso", b =>
                {
                    b.HasOne("FinanzasPersonales.Models.TipoIngreso", "TipoIngreso")
                        .WithMany()
                        .HasForeignKey("TipoIngresoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoIngreso");
                });

            modelBuilder.Entity("FinanzasPersonales.Models.Transaccion", b =>
                {
                    b.HasOne("FinanzasPersonales.Models.Egreso", "Egreso")
                        .WithMany()
                        .HasForeignKey("EgresoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinanzasPersonales.Models.Ingreso", "Ingreso")
                        .WithMany()
                        .HasForeignKey("IngresoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinanzasPersonales.Models.TipoPago", "TipoPago")
                        .WithMany()
                        .HasForeignKey("TipoPagoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinanzasPersonales.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Egreso");

                    b.Navigation("Ingreso");

                    b.Navigation("TipoPago");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
